### PR TITLE
add german terms (prefLabel, definition) to interactivityType.ttl

### PR DESCRIPTION
**Pull request by ComeIn-NRW**

### CODE REVIEW

**Comment by philbarker** [comment]
@ComeIn-NRW hi, sorry I didn't follow this up sooner, but was there a reason to close this PR? I would welcome translations anb was going to raise this during our call on Tues 7 Dec. We are finishing up some work on a new concept scheme so we could push a translation like this into the specs at the same time as publishing that.

**Comment by ComeIn-NRW** [comment]
> @ComeIn-NRW hi, sorry I didn't follow this up sooner, but was there a reason to close this PR? I would welcome translations anb was going to raise this during our call on Tues 7 Dec. We are finishing up some work on a new concept scheme so we could push a translation like this into the specs at the same time as publishing that.

I decided to submit it to [our working group](https://wiki.dnb.de/display/DINIAGKIM/OER-Metadatengruppe) first to discuss it as there's already another PR for adding german translations in another [fork](https://github.com/dini-ag-kim/lrmi/pulls).

I now suggested submitting a PR with translations till 6th of December

**Comment by philbarker** [comment]
That's great, thanks.

**Comment by ComeIn-NRW** [comment]
> That's great, thanks.

New PR: #37

**Pull request closed without merging**
